CUR_DIR := $(shell pwd)

hs:
	cfg=${CUR_DIR}/config/arch.py app=${CUR_DIR}/software make -C ../../../../ hs

sw:
	cfg=${CUR_DIR}/config/arch.py app=${CUR_DIR}/software make -C ../../../../ sw

run:
	cfg=${CUR_DIR}/config/arch.py app=${CUR_DIR}/software make -C ../../../../ run

runv:
	cfg=${CUR_DIR}/config/arch.py app=${CUR_DIR}/software make -C ../../../../ runv

rund:
	cfg=${CUR_DIR}/config/arch.py app=${CUR_DIR}/software make -C ../../../../ rund

pfto:
	make -C ../../../../ pfto