#!/usr/bin/env python3
# Copyright 2025 ETH Zurich and University of Bologna.
# SPDX-License-Identifier: Apache-2.0
#
# Generates test data header for SpMM with N:M sparsity.
# Supports fp16 and fp32 via --dtype flag.
#
# Usage:
#   python3 datagen.py -M 4 -K 8 -N 16 --n_sparse 2 --m_sparse 4
#   python3 datagen.py -M 4 -K 8 -N 16 --n_sparse 1 --m_sparse 4 --dtype fp16

import os
import sys
import argparse
import struct
import numpy as np


def to_hex(val, dtype):
    if dtype == 'fp16':
        return '0x{:04x}'.format(int(np.float16(val).view(np.uint16)))
    else:
        return '0x{:08x}'.format(struct.unpack('<I', struct.pack('<f', float(val)))[0])


def uint32_to_hex(u):
    return '0x{:08x}'.format(u & 0xFFFFFFFF)


def create_sparse_weight(K, N, n_sparse, m_sparse, rng, np_dtype):
    assert N % m_sparse == 0
    num_groups = N // m_sparse
    P_W = N * n_sparse // m_sparse

    W_dense = np.zeros((K, N), dtype=np_dtype)
    W_compact = np.zeros((K, P_W), dtype=np_dtype)
    indices = np.zeros((K, P_W), dtype=np.uint32)

    for k in range(K):
        compact_col = 0
        for g in range(num_groups):
            col_start = g * m_sparse
            positions = np.sort(rng.choice(m_sparse, size=n_sparse, replace=False))
            for s, pos in enumerate(positions):
                val = np_dtype(rng.uniform(-1.0, 1.0))
                W_dense[k, col_start + pos] = val
                W_compact[k, compact_col] = val
                indices[k, compact_col] = pos
                compact_col += 1

    return W_dense, W_compact, indices


def main():
    parser = argparse.ArgumentParser(description='SpMM data generator')
    parser.add_argument('-M', type=int, required=True)
    parser.add_argument('-K', type=int, required=True)
    parser.add_argument('-N', type=int, required=True)
    parser.add_argument('--n_sparse', type=int, default=2)
    parser.add_argument('--m_sparse', type=int, default=4)
    parser.add_argument('--dtype', type=str, default='fp32', choices=['fp16', 'fp32'])
    parser.add_argument('--seed', type=int, default=42)
    args = parser.parse_args()

    M_mat, K, N = args.M, args.K, args.N
    n_sparse, m_sparse = args.n_sparse, args.m_sparse
    rng = np.random.RandomState(args.seed)

    if args.dtype == 'fp16':
        np_dtype = np.float16
        c_elem_type = 'uint16_t'
        elem_bits = 16
        elem_bytes = 2
    else:
        np_dtype = np.float32
        c_elem_type = 'uint32_t'
        elem_bits = 32
        elem_bytes = 4

    P_W = N * n_sparse // m_sparse

    A = rng.uniform(-1.0, 1.0, (M_mat, K)).astype(np_dtype)
    W_dense, W_compact, indices = create_sparse_weight(K, N, n_sparse, m_sparse, rng, np_dtype)
    C = (A.astype(np.float32) @ W_dense.astype(np.float32)).astype(np_dtype)
    checksums = C.astype(np.float32).sum(axis=1).astype(np.float32)

    script_dir = os.path.dirname(os.path.abspath(__file__))
    header_path = os.path.join(script_dir, '..', 'include', 'data_spmm_fp32.h')

    with open(header_path, 'w') as f:
        f.write(f'// Auto-generated by datagen.py -- do not edit\n')
        f.write(f'// SpMM: C({M_mat}x{N}) = A({M_mat}x{K}) * W_sparse({K}x{N}), {args.dtype}\n')
        f.write(f'// Sparsity: {n_sparse}:{m_sparse}, P_W={P_W}\n\n')
        f.write('#ifndef DATA_SPMM_FP32_H\n')
        f.write('#define DATA_SPMM_FP32_H\n\n')
        f.write('#include <stdint.h>\n\n')
        f.write(f'#define SPMM_M {M_mat}\n')
        f.write(f'#define SPMM_K {K}\n')
        f.write(f'#define SPMM_N {N}\n')
        f.write(f'#define SPMM_PW {P_W}\n')
        f.write(f'#define SPMM_N_SPARSE {n_sparse}\n')
        f.write(f'#define SPMM_M_SPARSE {m_sparse}\n')
        f.write(f'#define DATA_TYPE_WIDTH {elem_bits}\n')
        f.write(f'#define DATA_TYPE_BYTE {elem_bytes}\n\n')

        # A [M x K]
        f.write(f'static const {c_elem_type} matrix_a_fp32[{M_mat * K}] = {{\n')
        for i in range(M_mat * K):
            f.write(f'  {to_hex(A.flat[i], args.dtype)},\n')
        f.write('};\n\n')

        # W compact [K x P_W]
        f.write(f'static const {c_elem_type} matrix_w_compact[{K * P_W}] = {{\n')
        for i in range(K * P_W):
            f.write(f'  {to_hex(W_compact.flat[i], args.dtype)},\n')
        f.write('};\n\n')

        # Indices [K x P_W] — always uint32
        f.write(f'static const uint32_t matrix_idx[{K * P_W}] = {{\n')
        for i in range(K * P_W):
            f.write(f'  {uint32_to_hex(indices.flat[i])},\n')
        f.write('};\n\n')

        # Golden C [M x N]
        f.write(f'static const {c_elem_type} matrix_c_golden_fp32[{M_mat * N}] = {{\n')
        for i in range(M_mat * N):
            f.write(f'  {to_hex(C.flat[i], args.dtype)},\n')
        f.write('};\n\n')

        # Checksums (always fp32)
        f.write(f'static const uint32_t matrix_c_checksum_fp32[{M_mat}] = {{\n')
        for i in range(M_mat):
            f.write(f'  {to_hex(checksums[i], "fp32")},\n')
        f.write('};\n\n')

        f.write('#endif // DATA_SPMM_FP32_H\n')

    print(f'Generated {header_path}')
    print(f'  M={M_mat}, K={K}, N={N}, P_W={P_W}, sparsity={n_sparse}:{m_sparse}, dtype={args.dtype}')


if __name__ == '__main__':
    main()
