#!/usr/bin/env python3
# Copyright 2025 ETH Zurich and University of Bologna.
# SPDX-License-Identifier: Apache-2.0
#
# Generates test data header for GEMM: C = A * B
# Supports fp16 and fp32.
#
# Usage:
#   python3 datagen.py -M 16 -K 16 -N 16                 # fp32 (default)
#   python3 datagen.py -M 16 -K 16 -N 16 --dtype fp16    # fp16

import os
import sys
import argparse
import struct
import numpy as np

def to_hex(val, dtype):
    if dtype == 'fp16':
        return '0x{:04x}'.format(int(np.float16(val).view(np.uint16)))
    else:
        return '0x{:08x}'.format(struct.unpack('<I', struct.pack('<f', float(val)))[0])

def main():
    parser = argparse.ArgumentParser(description='GEMM data generator')
    parser.add_argument('-M', type=int, required=True)
    parser.add_argument('-K', type=int, required=True)
    parser.add_argument('-N', type=int, required=True)
    parser.add_argument('--dtype', type=str, default='fp32', choices=['fp16', 'fp32'])
    parser.add_argument('--seed', type=int, default=42)
    args = parser.parse_args()

    M, K, N = args.M, args.K, args.N
    np.random.seed(args.seed)

    if args.dtype == 'fp16':
        np_dtype = np.float16
        c_elem_type = 'uint16_t'
        elem_bits = 16
        elem_bytes = 2
    else:
        np_dtype = np.float32
        c_elem_type = 'uint32_t'
        elem_bits = 32
        elem_bytes = 4

    A = np.random.uniform(-1.0, 1.0, (M, K)).astype(np_dtype)
    B = np.random.uniform(-1.0, 1.0, (K, N)).astype(np_dtype)
    C = (A.astype(np.float32) @ B.astype(np.float32)).astype(np_dtype)
    checksums = C.astype(np.float32).sum(axis=1).astype(np.float32)

    script_dir = os.path.dirname(os.path.abspath(__file__))
    header_path = os.path.join(script_dir, '..', 'include', 'data_fp32.h')

    with open(header_path, 'w') as f:
        f.write(f'// Auto-generated by datagen.py -- do not edit\n')
        f.write(f'// GEMM: C({M}x{N}) = A({M}x{K}) * B({K}x{N}), {args.dtype}\n\n')
        f.write('#ifndef DATA_FP32_H\n')
        f.write('#define DATA_FP32_H\n\n')
        f.write('#include <stdint.h>\n\n')
        f.write(f'#define GEMM_M {M}\n')
        f.write(f'#define GEMM_K {K}\n')
        f.write(f'#define GEMM_N {N}\n')
        f.write(f'#define DATA_TYPE_WIDTH {elem_bits}\n')
        f.write(f'#define DATA_TYPE_BYTE {elem_bytes}\n\n')

        f.write(f'static const {c_elem_type} matrix_a_fp32[{M * K}] = {{\n')
        for i in range(M * K):
            f.write(f'  {to_hex(A.flat[i], args.dtype)},\n')
        f.write('};\n\n')

        f.write(f'static const {c_elem_type} matrix_b_fp32[{K * N}] = {{\n')
        for i in range(K * N):
            f.write(f'  {to_hex(B.flat[i], args.dtype)},\n')
        f.write('};\n\n')

        f.write(f'static const {c_elem_type} matrix_c_golden_fp32[{M * N}] = {{\n')
        for i in range(M * N):
            f.write(f'  {to_hex(C.flat[i], args.dtype)},\n')
        f.write('};\n\n')

        # Checksums always fp32 for verification
        f.write(f'static const uint32_t matrix_c_checksum_fp32[{M}] = {{\n')
        for i in range(M):
            f.write(f'  {to_hex(checksums[i], "fp32")},\n')
        f.write('};\n\n')

        f.write('#endif // DATA_FP32_H\n')

    print(f'Generated {header_path} (M={M}, K={K}, N={N}, dtype={args.dtype})')

if __name__ == '__main__':
    main()
