#!/usr/bin/env python3
# Copyright 2025 ETH Zurich and University of Bologna.
# SPDX-License-Identifier: Apache-2.0
#
# Generates HBM preload ELF for fp32 GEMM: C = A * B
# Matrices are placed in HBM and loaded by the kernel via DMA.
#
# HBM layout (starting at offset 0):
#   [0..63]   metadata: uint32_t[16] = {A_addr, B_addr, C_addr, G_addr, M, K, N, ...}
#   [64..]    A (M*K float32), B (K*N float32), C (M*N float32), Golden (M*N float32)
#
# Usage:
#   python3 hbm_datagen.py -M 32 -K 128 -N 128

import os
import sys
import argparse
import numpy as np

# Add the preload utility to path
script_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(script_dir, '..', '..', '..', '..', '..', 'soft_hier', 'flex_cluster_utilities'))
import preload as pld

def make_preload_elf_rv32(output_file_path, np_arrays):
    """Wrapper around pld.make_preload_elf that patches for riscv32 toolchain."""
    import preload as _pld
    # Monkey-patch os.system calls to use riscv32 toolchain
    original_system = os.system
    def patched_system(cmd):
        cmd = cmd.replace('riscv64-unknown-elf-', 'riscv32-unknown-elf-')
        return original_system(cmd)
    os.system = patched_system
    try:
        _pld.make_preload_elf(output_file_path, np_arrays)
    finally:
        os.system = original_system

def main():
    parser = argparse.ArgumentParser(description='FP32 GEMM HBM preload generator')
    parser.add_argument('-M', type=int, required=True, help='Rows of A and C')
    parser.add_argument('-K', type=int, required=True, help='Columns of A / Rows of B')
    parser.add_argument('-N', type=int, required=True, help='Columns of B and C')
    parser.add_argument('--seed', type=int, default=42, help='Random seed')
    parser.add_argument('-o', type=str, default=None, help='Output ELF path')
    args = parser.parse_args()

    M, K, N = args.M, args.K, args.N
    np.random.seed(args.seed)

    # Generate random float32 matrices
    A = np.random.uniform(-1.0, 1.0, (M, K)).astype(np.float32)
    B = np.random.uniform(-1.0, 1.0, (K, N)).astype(np.float32)
    C = np.zeros((M, N), dtype=np.float32)
    Golden = (A @ B).astype(np.float32)

    # Compute HBM addresses (64-byte aligned, metadata in first 64 bytes)
    ALIGN = 64
    meta_size = ALIGN  # 64 bytes for metadata
    A_addr = meta_size
    B_addr = A_addr + ((A.nbytes + ALIGN - 1) // ALIGN) * ALIGN
    C_addr = B_addr + ((B.nbytes + ALIGN - 1) // ALIGN) * ALIGN
    G_addr = C_addr + ((C.nbytes + ALIGN - 1) // ALIGN) * ALIGN

    # Metadata: addresses and dimensions as uint32
    metadata = np.array([A_addr, B_addr, C_addr, G_addr, M, K, N, 0,
                         0, 0, 0, 0, 0, 0, 0, 0], dtype=np.uint32)

    # Build preload ELF
    output_path = args.o if args.o else os.path.join(script_dir, '..', '..', 'preload', 'preload.elf')
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    make_preload_elf_rv32(output_path, [metadata, A, B, C, Golden])

    # Also generate data_fp32.h that enables HBM mode
    header_path = os.path.join(script_dir, '..', 'include', 'data_fp32.h')
    with open(header_path, 'w') as f:
        f.write('// Auto-generated by hbm_datagen.py -- HBM preload mode\n')
        f.write('#ifndef DATA_FP32_H\n')
        f.write('#define DATA_FP32_H\n')
        f.write('#define USE_HBM_PRELOAD\n')
        f.write('#endif\n')

    total_size = G_addr + Golden.nbytes
    print(f'Generated {output_path}')
    print(f'Generated {header_path} (HBM preload mode)')
    print(f'  GEMM: C({M}x{N}) = A({M}x{K}) * B({K}x{N}), float32')
    print(f'  HBM layout: A@0x{A_addr:X} B@0x{B_addr:X} C@0x{C_addr:X} G@0x{G_addr:X}')
    print(f'  Total HBM: {total_size/1024:.1f} KB')

if __name__ == '__main__':
    main()
