#ifndef _DEEPSEEK_CONFIG_H_
#define _DEEPSEEK_CONFIG_H_

// #define DATA_TYPE_WIDTH 			16
// #define DATA_TYPE_BYTE  			2
// #define REDMULE_COMPUTE_TYPE 		REDMULE_NONE_16

#define DATA_TYPE_WIDTH 			8
#define DATA_TYPE_BYTE  			1
#define REDMULE_COMPUTE_TYPE 		REDMULE_UINT_8

#define COLLECTIVE_REDSUM_TYPE 		COLLECTIVE_REDADD_FP_16
#define COLLECTIVE_REDMAX_TYPE 		COLLECTIVE_REDMAX_FP_16

// #define DATA_TYPE_FP

#define DEEPSEEK_EMBEDDED_LENGTH 	7168

#define DEEPSEEK_MOE_ROUTED_EXPERT 	256
#define DEEPSEEK_MOE_ACTIVE_EXPERT 	8

#define STR(x) #x
#define XSTR(x) STR(x)


#endif